### ISSUE TITLE
(SA) Menu looks like a block, cant move it or size it

### ISSUE THREAD

**Issue by aswertyStuff** [user-grinch/GrinchTrainer-III-VC-SA#1]
So cheat menu is archived, so this is why im posting issue here, there is no globals.ini file in here so, how?

**Comment by aswertyStuff** [comment]
-Cleo Plus

**Comment by aswertyStuff** [comment]
Maybe it seems like its gotta be something to do with silentpatch, but without silent patch the mod would not work at all.

**Comment by user-grinch** [comment]
This isn't a repository for CheatMenu but rather the new trainer. Join the discord server someone might help you there.
