### ISSUE TITLE
[SA] Crash when doing skydiving

### ISSUE THREAD

**Issue by KiloRyu** [user-grinch/GrinchTrainer-III-VC-SA#10]
Pretty much self explanatory, the game crashed when CJ doing skydiving.
Also crashed on "A Home In The Hill" mission, in the last flight school lesson, and bailing from a plane in the midair.

CJ will freeze in skydiving position and the game crashed, sometimes doesn't crashed immediately, instead CJ will aggressively spinning counterclockwise in the moment before the game crashed

Also tested on clean copy of GTA SA, with essentials included. Same bug occured.

**Comment by user-grinch** [comment]
Can you test without god mode enanbled?

**Comment by KiloRyu** [comment]
Yup, the bug was solved by disabling god mode.

And also updated this trainer up to date from discord and it seems there's no problem so far, including this bug
