### ISSUE TITLE
[SA] Game crashes when getting wanted levels

### ISSUE THREAD

**Issue by sandenbergmelo** [user-grinch/GrinchTrainer-III-VC-SA#12]
Using [Chash Info](https://www.mixmods.com.br/2022/09/crashinfo/) to show the crash:
![image](https://github.com/user-attachments/assets/4153739d-6898-405d-91d5-46a17d086251)

Logs:
[gta_sa.exe_2024-09-06_21-43-26.log](https://github.com/user-attachments/files/16913851/gta_sa.exe_2024-09-06_21-43-26.log)

**Comment by user-grinch** [comment]
How to reproduce?

**Comment by sandenbergmelo** [comment]
> How to reproduce?

It was caused by an error on my part when installing. Sorry.
