### ISSUE TITLE
Conflicts with mods by Ryosuke839 

### ISSUE THREAD

**Issue by SammySites2206** [user-grinch/GrinchTrainer-III-VC-SA#3]
I have been liking the mod so far, however the mod causes other mods (mostly those that add cheat or command strings) to crash when activating them, it happened with mods done by Ryosuke839 such as Master Spark or Time Stop, which cause the game to crash when you try to activate them, I think it happens with other mods done by them and other mods which serve similar functions such as superpowers.

It also happened with a climbing mod I got, the game crashed. However, after uninstalling the cheat menu, all mods work perfectly, I do hope it manages to get fixed because personally I am starting to like this new cheat menu and might consider it an amazing alternative to RZL Trainer, or tell others to use both trainers, since both of them have some features that one another doesn't have.

**Comment by user-grinch** [comment]
Can you link to some mods that cause crash?

**Comment by SammySites2206** [comment]
It has been happening to me with a FEW mods that just are .cs (meaning, that you only need to drag the file to the CLEO folder without the need of modloader)

For me, it happened with mods from Ryosuke839, however the only ones I have are Fish, Time Stopper and Master Spark, when I use their respective commands (after activating it for the former and writing it like a cheatcode for the 2 latter) the game suddenly crashes, and I can't use these mods unless I uninstall GrinchTrainer, the crash also happens with a mod I installed recently called Climbmod. (where it crashes when you try to climb in a structure)

Strangely, I do have some a mod done by Ryosuke839 which works perfectly without problems when you have GrinchTrainer installed, that being Gravity Gun, also, someone at your Discord server pointed me out that they have Master Spark installed along with 30+ mods and they have experienced no issues while using it with GrinchTrainer, I even removed all my mods (including RZL Trainer) except for Master Spark, and the crash still goes on, and I am not sure if I am missing something needed for the mod (such as a limit adjuster), or the mods collide with features present in GrinchTrainer.

Here I am leaving the links of the mods I mentioned (and experienced crashes with)

http://hotmist.ddo.jp/cleomod/index.html (Ryosuke's mod page, where Fishing, Master Spark, Time Stopping and Gravity Gun can be downloaded)

https://libertycity.net/files/gta-san-andreas/196467-climbmod-v2-3-pc-mobile.html (Climbmod)

**Comment by user-grinch** [comment]
> It has been happening to me with a FEW mods that just are .cs (meaning, that you only need to drag the file to the CLEO folder without the need of modloader)
> 
> For me, it happened with mods from Ryosuke839, however the only ones I have are Fish, Time Stopper and Master Spark, when I use their respective commands (after activating it for the former and writing it like a cheatcode for the 2 latter) the game suddenly crashes, and I can't use these mods unless I uninstall GrinchTrainer, the crash also happens with a mod I installed recently called Climbmod. (where it crashes when you try to climb in a structure)
> 
> Strangely, I do have some a mod done by Ryosuke839 which works perfectly without problems when you have GrinchTrainer installed, that being Gravity Gun, also, someone at your Discord server pointed me out that they have Master Spark installed along with 30+ mods and they have experienced no issues while using it with GrinchTrainer, I even removed all my mods (including RZL Trainer) except for Master Spark, and the crash still goes on, and I am not sure if I am missing something needed for the mod (such as a limit adjuster), or the mods collide with features present in GrinchTrainer.
> 
> Here I am leaving the links of the mods I mentioned (and experienced crashes with)
> 
> http://hotmist.ddo.jp/cleomod/index.html (Ryosuke's mod page, where Fishing, Master Spark, Time Stopping and Gravity Gun can be downloaded)
> 
> https://libertycity.net/files/gta-san-andreas/196467-climbmod-v2-3-pc-mobile.html (Climbmod)

Appreciate the detailed response. Taking a look at it.

**Comment by user-grinch** [comment]
Just tested with the latest beta build. The issue seems to have been resolved.
